stages:
  preprocess:
    cmd: python src/preprocess.py --input 
      /Users/mahamatabakarassouna/Downloads/MLOps_Intro/iris.json --output 
      data/iris_clean.csv
    deps:
    - iris.json
    - src/preprocess.py
    outs:
    - data/iris_clean.csv
