services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env                   # load environment variables from .env
    volumes:
      - ./models:/app/models   # mount local models folder
    secrets:
      - api_key

secrets:
  api_key:
    file: ./secrets/api_key.txt
