name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'day06/**'
      - '.github/workflows/cic.yml'
      - 'requirements.txt'
  pull_request:
    branches:
      - main
    paths:
      - 'day06/**'
      - '.github/workflows/cic.yml'
      - 'requirements.txt'

jobs:
  test:
    name: Run Tests on Python 3.12
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python 3.12
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # 3. Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run pytest on tests inside day06 folder
      - name: Run Tests
        run: python -m pytest ./day06/tests/test_main.py -v
