name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      # 1. Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python from matrix
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3. Cache pip dependencies
     # - name: Cache pip
      #  uses: actions/cache@v3
       # with:
        #  path: ~/.cache/pip
         # key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          #restore-keys: |
           # ${{ runner.os }}-pip-

      # 4. Upgrade pip and install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run pytest
      - name: Run Tests
        run: python -m pytest ./tests/test_main.py -v
