name: Manual Dispatch Pipeline

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to print'
        required: true
        default: 'Hello from manual dispatch!'
      run_extra_step:
        description: 'Run extra step?'
        required: false
        default: false
        type: boolean

jobs:
  manual_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print message
        run: |
          echo "Message: ${{ github.event.inputs.message }}"

      - name: Extra step
        if: ${{ github.event.inputs.run_extra_step }}
        run: |
          echo "Running the extra step because run_extra_step is true!"
